# Generated by Django 4.0.3 on 2022-03-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0005_math_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'ordering': ['-id']},
        ),
    ]
