# Generated by Django 4.0.3 on 2022-03-29 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
